// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciDersBilgisi;

#nullable disable

namespace OgrenciDersBilgisi.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OgrenciDersBilgisi.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HarfNotu")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Kredi")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dersler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "İleri Programlama",
                            HarfNotu = "A",
                            Kod = "BİL256",
                            Kredi = 3.0
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Genel Matematik",
                            HarfNotu = "B",
                            Kod = "MAT178",
                            Kredi = 3.0
                        },
                        new
                        {
                            Id = 3,
                            Ad = "İngilizce II",
                            HarfNotu = "D",
                            Kod = "İNG262",
                            Kredi = 2.0
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Seçmeli Ders I",
                            HarfNotu = "C",
                            Kod = "SEÇ401",
                            Kredi = 1.0
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Olasılık",
                            HarfNotu = "F",
                            Kod = "İST244",
                            Kredi = 4.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
